### ISSUE TITLE
React 빈 프로젝트 생성

### ISSUE THREAD

**Issue by mjin1220** [Do-Anything-With/oc-front#1]
React 빈 프로젝트 생성

패키지매니저는 yarn 최신 버전을 사용하도록 하자!
스크립트언어로는 JS 최신 문법을 따르도록 한다.

**Comment by devowov** [comment]
LF ~ 관련 에러 오류 발생
1. https://blog.naver.com/helloahri21/222499526104 (명령어 실행)
2. gitignore파일 생성 후 진행
